name: Compile Test Codebases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Build
      shell: pwsh
      run: |
        cd main 
        ls
        dotnet build DMCompiler --configuration Release /m
    - name: Compile TestGame
      shell: pwsh
      run: cd main/DMCompiler | dotnet run main\TestGame\environment.dme --configuration Release --no-build
    - name: Checkout Modified /tg/station
      uses: actions/checkout@v2
      with:
        repository: wixoaGit/tgstation
        path: tg
    - name: Compile Modified /tg/station
      run: cd main/DMCompiler | dotnet run tg\tgstation.dme --configuration Release --no-build
